### ISSUE TITLE
Provide longer names for functions.

### ISSUE THREAD

**Issue by phadej** [ku-fpg/natural-transformation#11]
`nat` and `run` are convenient, but can potentially clash with many things.

Would adding e.g. `makeNT` and `applyNT`, or `mkNT` and `appNT` be ok?

_EDIT:_ I really blame the one who named natural numbers and/or natural transformations...

**Comment by RyanGlScott** [comment]
I wouldn't object to it. We've already discussed adding more combinators with an `-NT` suffix [here](https://github.com/ku-fpg/natural-transformation/issues/9#issuecomment-172121060), so this renaming would at least be consistent with that new direction.
