### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by phadej** [ku-fpg/natural-transformation#15]
Is there something holding up the release?

**Comment by RyanGlScott** [comment]
Sorry, I've been occupied with a PLDI deadline for a while. I'll look into making a new release some time this week.

**Comment by RyanGlScott** [comment]
I've uploaded [`natural-transformation-0.4`](http://hackage.haskell.org/package/natural-transformation-0.4) to Hackage.

**Comment by phadej** [comment]
Thanks!
