### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/natural-transformation#2]
Now that we have a repo for this, we should finish our conversation about what to name `(:~>)`, `Nat`, `($$)`, `Transformation`, and `(#)` (or should they be changed at all?).

Originally started [here](https://github.com/ku-fpg/wakarusa/issues/2).

**Comment by andygill** [comment]
I've just pushed some changes to Wakarusa that might help. I'm thinking we use ($$), :~>, and leave # as part of Wakarusa.

**Comment by RyanGlScott** [comment]
What do you mean by leaving `(#)` as a part of Wakarusa? Are you proposing a different name in `natural-transformation`? Removing the `Transformation` type class? Something else?

**Comment by andygill** [comment]
I mean leave (#) and the Transformation class in Wakarusa, but move Natural (now called `:~>`), and other supporting definitions, into natural-transformation.

**Comment by RyanGlScott** [comment]
In that case, what of using `(#)` in `blank-canvas`? It seemed to me that using `Transformation` instances (without necessarily having to use `:~>`) was the cleanest approach.

**Comment by andygill** [comment]
Good point. Not sure. Yes, `Transformation` is cleaner in this example. Perhaps a different module called Transformation, in the natural-transformation package?

**Comment by RyanGlScott** [comment]
At the moment, I have `:~>` in `Control.Natural` and `Transformation` in `Control.Transformation`, which seems pretty straightforward (unless you want to imply a closer relationship, e.g., `Control.Transformation` and `Control.Transformation.Natural`).

**Comment by RyanGlScott** [comment]
I'm going to close this for now, since it seems like something of a consensus has been reached on the names. If you disagree, please reopen this issue. Otherwise, I'll go ahead and upload this to Hackage sometime by the end of the week.
