### ISSUE TITLE
Bump hackage version

### ISSUE THREAD

**Issue by superfunc** [ku-fpg/natural-transformation#4]
We didn't export `~>` which some examples needed, so we should bump the hackage version to reflect this.

**Comment by andygill** [comment]
Oops. Yes, we'll need to re-release n-t. Perhaps we should have tried changing wakarusa first.

**Comment by superfunc** [comment]
wakarusa has already been updated to reflect the new nat-trans

**Comment by RyanGlScott** [comment]
I deliberately didn't include `type f ~> g = forall x. f x -> g x` in `natural-transformation`, since the rules for legal characters in type operators wouldn't allow `~>` prior to GHC 7.6 (see [here](https://github.com/ku-fpg/wakarusa/issues/2#issuecomment-74906331)). To allow `natural-transformation` to keep backwards compatibility, I'd recommend just including `~>` in `wakarusa` itself (which intends to be more bleeding-edge).

**Comment by superfunc** [comment]
I think 7.6 is a reasonable minimum bar to ask people to have.

**Comment by RyanGlScott** [comment]
I'm inclined to agree, but keep in mind that:
- `natural-transformation` is going to be used in `blank-canvas` eventually, which supports GHC 7.4.
- Debian currently uses GHC 7.4.
- `natural-transformation` isn't using any code that requires bleeding-edge features of GHC, so we'd be preventing users of older GHCs the ability to use `natural-transformation` just for the sake of a type synonym.

**Comment by superfunc** [comment]
is there a way to do a conditional export?

**Comment by andygill** [comment]
Good observations from both of you! We've already got a version on hackage that works with 7.4, and I support now requiring 7.6 going forward. 
- It would be nice if blank-canvas still works with at least 7.6, which is 2 years old now.
- Wakarusa requiring 7.8.X is just fine; its cutting edge. Wakarusa may even require 7.10 for technical reasons to do with the monad -> applicative connection.

**Comment by RyanGlScott** [comment]
We could surround `~>` with CPP pragmas (i.e., `#if __GLASGOW_HASKELL__ >= 706`), but it's my understanding that conditionally exporting API features is considered bad practice, since all downstream users of the library will also have to check if `__GLASGOW_HASKELL__ >= 706` if they attempt to use `~>`.

Personally, I feel that type synonyms are extremely cheap to define (or redefine) if you need them, so I don't see any issue with leaving out `~>`, since `:~>` is the thing with a `Transformation` instance anyway.

**Comment by superfunc** [comment]
I agree they are easy. But, with 7.10 around the corner, I feel like requiring two versions behind is really reasonable.

**Comment by RyanGlScott** [comment]
Works for me. In that case, we should probably move `~>` from `Control.Transformation` to `Control.Natural` (where `:~>` is defined), and remove GHCs 7.0 and 7.4 from the Travis-CI build, since they won't build with `~>` present.

**Comment by RyanGlScott** [comment]
Also, we probably shouldn't be encoding the free theorem as a rewrite rule, as Edward Kmett pointed out in e-mail correspondence:

> Then there are concerns like that stating the rules for a natural transformation follow from parametricity in Haskell. RULES in the implementation means that you get thrust out of SafeHaskell and silently change the semantics of code. There isn't a clear reason to choose one orientation of the RULE against the other here, so its better spelled out in a comment than in a rewrite rule ,lest you get very surprising behavior.

**Comment by andygill** [comment]
This RULES problem seems like a bug in RULES, **especially** for [~] RULES.

**Comment by RyanGlScott** [comment]
Is there any particular reason to favor `(r #) . fmap h` over `fmap h . (r #)`, though? I'm not sure what benefit it provides that requires changing the code.

**Comment by andygill** [comment]
We want to start encouraging library owners to provide RULES, so that HERMIT can use them. It might be the wrong time to fight this fight, though.

**Comment by xich** [comment]
RULES can have performance effects even when inactive. (Though it's honestly hard to quantify. They affect things like free variables and mutual recursion, which affects the inliner and simplifier.) I think we shouldn't "fight that fight" until we have a dedicated means of parsing HERMIT lemmas at the source level. There are a few design decisions to make there, such as whether to parse source haskell or Core or both. Such a feature likely requires changes to GHC's parser, so even if we figure it out now, won't be released for at least a year (7.12).

Though I haven't been following exactly what's going on here, so not sure if any of my comment actually applies. ;-)

**Comment by andygill** [comment]
Fair enough.  We should remove the RULES, and have them as comments.

**Comment by RyanGlScott** [comment]
Released on Hackage as `natural-transformation-0.2`.
