### ISSUE TITLE
LANGUAGE_PolyKinds cpp

### ISSUE THREAD

**Issue by andygill** [ku-fpg/natural-transformation#7]
@roboguy13 @RyanGlScott 

Can we removed the PolyKinds cpp-ism? 

http://damianfral.github.io/ghcaniuse/ shows PolyKinds since 7.4, and we (will) only support 7.8 and 7.10.

**Comment by RyanGlScott** [comment]
Sure thing.  2a53dfb removes most of these CPP kludges (save for some FTP-related `#ifdefs`, which can be removed when GHC 7.8 support is dropped).

**Comment by andygill** [comment]
Thanks!
